Add Works and about me sections to portfolio.
ernestmusong/Portfolio pull request #3
Opened 2023-01-13 21:49 UTC by ernestmusong

I have added "works" (projects) and  "about me" sections to my portfolio

2023-01-13 23:34 UTC, Kossi-stack requested changes
## Hi @ernestmusong,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-13 23:34 UTC, Kossi-stack commented on index.html
> +                        <button>ruby on rails</button>
- [ ] Kindly list all technologies in a list of "ul" and each of them  in "li"

2023-01-13 23:34 UTC, Kossi-stack commented on index.html
> +                <div class=" card-buttons-wrap">
- [ ] Kindly list all technologies in a list of "ul" and each of them in "li"

2023-01-13 23:34 UTC, Kossi-stack commented on index.html
> +                    <button>ruby on rails</button>
- [ ] Kindly list all category technologies in a list of "ul" and each of them in "li"

2023-01-13 23:34 UTC, Kossi-stack commented on index.css
> +  display: flex;
- [ ] Kindly use a display grid so it helps you align and balance with the design

2023-01-14 00:49 UTC, ernestmusong commented on index.css
> +  display: flex;
> * [ ]  Kindly use a display grid so it helps you align and balance with the design

Hi @Kossi-stack, thank you for your feedback. I have made all changes as indicated by you. However I think the headline section doesn't require a display grid as specified in the project's requirements [here](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md)

2023-01-14 00:59 UTC, Owusu-Desmond approved these changes
Hi @ernestmusong , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 06:58 UTC, merged